// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/aspects_chart/[shop_id].tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/rating/[page].tsx";
import * as $5 from "./routes/statistics.tsx";
import * as $$0 from "./islands/Layout.tsx";
import * as $$1 from "./islands/ShopCard.tsx";
import * as $$2 from "./islands/Sidebar.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/aspects_chart/[shop_id].tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/rating/[page].tsx": $4,
    "./routes/statistics.tsx": $5,
  },
  islands: {
    "./islands/Layout.tsx": $$0,
    "./islands/ShopCard.tsx": $$1,
    "./islands/Sidebar.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
